name: Auto build for windows

on: push

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
          python-version: '3.11'
          architecture: x64
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip install pyinstaller tornado
        pip install -r requirements.txt
        
    - name: edit accesser.spec
      run: |
        $libdir = python -c 'import os.path, tld; print(repr(os.path.dirname(tld.__file__))[1:-1])'
        ((Get-Content -path ./accesser.spec -Raw) -replace '{{tld_path}}',$libdir) | Set-Content -Path ./accesser.spec
        ((Get-Content -path ./config.json.default -Raw) -replace '"logfile": null','"logfile": "Accesser.log"') | Set-Content -Path ./config.json.default
        cat accesser.spec
    - name: Package Application
      run: |
        pyinstaller accesser.spec
    - uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: ./dist/accesser.exe
